# AAI614: Data Science & its Applications

*Notebook 3.2: Practice with Data Cleaning*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%203/Notebook3.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

Exercise I. Load the following datafile from GitHub

In [13]:
grads = pd.read_csv("https://raw.githubusercontent.com/harmanani/AAI614/main/Week%203/grads.csv")

In [14]:
grads

,Student Name,Avg Hours Studies per Week,GPA,University,Sense of Humour (0-5),Salary
0,George,20,NaN,NYU,3.0,$40k
1,Jerry,35,3.5,Columbia,5.0,$80k
2,Elaine,55,4.0,Columbia,4.2,$60k
3,Cosmo,5,2.0,City College,2.0,$25k
4,Newman,25,2.8,City College,0.0,$50k
5,Frank,35,3.0,Festivus Uni,NaN,$40k
6,Estelle,100,3.2,Festivus Uni,1.7,$0k
7,Leo,15,2.4,Festivus Uni,0.0,$35k
8,Rachel,50,4.0,Columbia,NaN,$75k

Question 1: Identify all the outliers in the above data.  Justify your answers using objective measures.

Looking at "Avg Hours Studies per Week," the values are 20, 35, 55, 5, 25, 35, 100, 15, 50. The mean is about 38 and the values mostly cluster between 5 and 55. Estelle's 100 sits far above the rest, roughly 60+ hours beyond the next highest value (55), which is a big enough gap to call it an outlier by inspection, and it's also unrealistic since it implies over 14 hours of studying every day with no breaks. For "Salary," values are 40, 80, 60, 25, 50, 40, 0, 35, 75 (in thousands). Most cluster between 25k and 80k, and Estelle's $0k breaks that pattern sharply, especially since she has a decent GPA (3.2) and the highest reported study hours, so earning nothing doesn't fit the rest of her profile. GPA and Sense of Humour values, by contrast, stay within a reasonable, tight range and don't show any similar jump, so no outliers there.

Question 2: There are various data that are missing.  Fill-in the missing data or delete the rows/columns that you think you should delete.  Justify your answer

The code fills in the two missing values rather than deleting any rows or columns. George is missing his GPA, and Frank and Rachel are missing their Sense of Humour score, that's only one gap per row out of six total columns, so each of those rows still holds five good, usable data points. Deleting those rows would mean throwing away all of that other information just to get rid of one missing cell, which is a poor trade-off, especially with a dataset this small (only 9 students to begin with). Instead, the code uses fillna() with the column mean for GPA and for Sense of Humour,

In [15]:
grads['GPA'] = grads['GPA'].fillna(grads['GPA'].mean())
grads['Sense of Humour (0-5)'] = grads['Sense of Humour (0-5)'].fillna(grads['Sense of Humour (0-5)'].mean())

grads

,Student Name,Avg Hours Studies per Week,GPA,University,Sense of Humour (0-5),Salary
0,George,20,3.1125,NYU,3.000000,$40k
1,Jerry,35,3.5000,Columbia,5.000000,$80k
2,Elaine,55,4.0000,Columbia,4.200000,$60k
3,Cosmo,5,2.0000,City College,2.000000,$25k
4,Newman,25,2.8000,City College,0.000000,$50k
5,Frank,35,3.0000,Festivus Uni,2.271429,$40k
6,Estelle,100,3.2000,Festivus Uni,1.700000,$0k
7,Leo,15,2.4000,Festivus Uni,0.000000,$35k
8,Rachel,50,4.0000,Columbia,2.271429,$75k

Question 3: Reload the data and fill-in the data using mean method as well as the frequent method.

This code reloads the original dataset fresh (so it's unaffected by the fill already applied in Question 2), then creates two separate copies to compare imputation strategies. One copy fills the missing GPA and Sense of Humour values using the mean, the average of each column, which works well here since both are numeric scores that vary somewhat continuously. The other copy fills the same missing values using the mode, the most frequently occurring value in each column, which is typically better suited to categorical or repeated-value data rather than continuous scores.

In [16]:
grads_reload = pd.read_csv("https://raw.githubusercontent.com/harmanani/AAI614/main/Week%203/grads.csv")

grads_mean = grads_reload.copy()
grads_mean['GPA'] = grads_mean['GPA'].fillna(grads_mean['GPA'].mean())
grads_mean['Sense of Humour (0-5)'] = grads_mean['Sense of Humour (0-5)'].fillna(grads_mean['Sense of Humour (0-5)'].mean())

grads_freq = grads_reload.copy()
grads_freq['GPA'] = grads_freq['GPA'].fillna(grads_freq['GPA'].mode()[0])
grads_freq['Sense of Humour (0-5)'] = grads_freq['Sense of Humour (0-5)'].fillna(grads_freq['Sense of Humour (0-5)'].mode()[0])

print("Mean method:")
print(grads_mean)
print("\nMost frequent (mode) method:")
print(grads_freq)

Mean method:
  Student Name  Avg Hours Studies per Week     GPA     University  \
0       George                          20  3.1125            NYU
1        Jerry                          35  3.5000       Columbia
2       Elaine                          55  4.0000       Columbia
3        Cosmo                           5  2.0000   City College
4       Newman                          25  2.8000   City College
5        Frank                          35  3.0000   Festivus Uni
6      Estelle                         100  3.2000  Festivus Uni
7          Leo                          15  2.4000   Festivus Uni
8       Rachel                          50  4.0000       Columbia

   Sense of Humour (0-5) Salary
0               3.000000   $40k
1               5.000000   $80k
2               4.200000   $60k
3               2.000000   $25k
4               0.000000   $50k
5               2.271429   $40k
6               1.700000    $0k
7               0.000000   $35k
8               2.271429   $75k

Most frequent (mode) method:
  Student Name  Avg Hours Studies per Week  GPA     University  \
0       George                          20  4.0            NYU
1        Jerry                          35  3.5       Columbia
2       Elaine                          55  4.0       Columbia
3        Cosmo                           5  2.0   City College
4       Newman                          25  2.8   City College
5        Frank                          35  3.0   Festivus Uni
6      Estelle                         100  3.2  Festivus Uni
7          Leo                          15  2.4   Festivus Uni
8       Rachel                          50  4.0       Columbia

   Sense of Humour (0-5) Salary
0                    3.0   $40k
1                    5.0   $80k
2                    4.2   $60k
3                    2.0   $25k
4                    0.0   $50k
5                    0.0   $40k
6                    1.7    $0k
7                    0.0   $35k
8                    0.0   $75k

Exercise II. Run the cell below to create a new dataframe called `df_miss`.  Its first column will contain some missing values.

In [17]:
import pandas as pd
import numpy as np
import random

nrows = 10
ncols = 5

# set a seed for random number generation
np.random.seed(314)
# create an array filled with random data
data = np.array(np.random.rand(nrows, ncols))
# put the data to a pandas dataframe
df_miss = pd.DataFrame(data)
# rename the columns
df_miss.columns = ['col_'+str(ii) for ii in range(ncols)]

# randomly set some values to missing
ix0 = np.random.randint(nrows, size=3)
ix1 = np.random.randint(nrows, size=3)

df_miss['col_0'][ix0] = np.nan
df_miss['col_1'][ix1] = np.nan

print(df_miss)

      col_0     col_1     col_2     col_3     col_4
0       NaN       NaN  0.265048  0.783205  0.918001
1  0.827355       NaN  0.260480  0.911763  0.260757
2  0.766376  0.261531  0.122291  0.386006  0.840081
3       NaN       NaN  0.633110  0.584766  0.581232
4  0.677205  0.687155  0.438927  0.320927  0.570552
5       NaN  0.861074  0.834805  0.105766  0.060408
6  0.596882  0.792395  0.226356  0.535201  0.136066
7  0.372244  0.151977  0.429822  0.792706  0.406957
8  0.177850  0.909252  0.545331  0.100497  0.718721
9  0.978429  0.309776  0.260126  0.662900  0.139720

C:\Users\USER\AppData\Local\Temp\ipykernel_20380\310065607.py:21: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_miss['col_0'][ix0] = np.nan
C:\Users\USER\AppData\Local\Temp\ipykernel_20380\310065607.py:22: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_miss['col_1'][ix1] = np.nan

Impute the missing values (NaN) in `col_0` (but not `col_1`) with the median.  Store the values in the dataframe by using the parameter `inplace`.  Print the dataframe.

In [18]:
df_miss['col_0'].fillna(df_miss['col_0'].median(), inplace=True)
print(df_miss)

      col_0     col_1     col_2     col_3     col_4
0  0.677205       NaN  0.265048  0.783205  0.918001
1  0.827355       NaN  0.260480  0.911763  0.260757
2  0.766376  0.261531  0.122291  0.386006  0.840081
3  0.677205       NaN  0.633110  0.584766  0.581232
4  0.677205  0.687155  0.438927  0.320927  0.570552
5  0.677205  0.861074  0.834805  0.105766  0.060408
6  0.596882  0.792395  0.226356  0.535201  0.136066
7  0.372244  0.151977  0.429822  0.792706  0.406957
8  0.177850  0.909252  0.545331  0.100497  0.718721
9  0.978429  0.309776  0.260126  0.662900  0.139720

C:\Users\USER\AppData\Local\Temp\ipykernel_20380\177808035.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_miss['col_0'].fillna(df_miss['col_0'].median(), inplace=True)

Impute the missing values in `col_1` with value 0.  Store the values in the dataframe by using the parameter `inplace`.  Print the dataframe.

In [19]:
df_miss['col_1'].fillna(0, inplace=True)
print(df_miss)

      col_0     col_1     col_2     col_3     col_4
0  0.677205  0.000000  0.265048  0.783205  0.918001
1  0.827355  0.000000  0.260480  0.911763  0.260757
2  0.766376  0.261531  0.122291  0.386006  0.840081
3  0.677205  0.000000  0.633110  0.584766  0.581232
4  0.677205  0.687155  0.438927  0.320927  0.570552
5  0.677205  0.861074  0.834805  0.105766  0.060408
6  0.596882  0.792395  0.226356  0.535201  0.136066
7  0.372244  0.151977  0.429822  0.792706  0.406957
8  0.177850  0.909252  0.545331  0.100497  0.718721
9  0.978429  0.309776  0.260126  0.662900  0.139720

C:\Users\USER\AppData\Local\Temp\ipykernel_20380\2213679435.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_miss['col_1'].fillna(0, inplace=True)